### ISSUE TITLE
Add Licence

### ISSUE THREAD

**Issue by vlcinsky** [mansenfranzen/autodoc_pydantic#10]
I did not find any licence terms within the project.

Consider adding some (what about MIT? BSD? - you are the author).

Thanks for your plugin - seems very practical and looks great.

**Comment by mansenfranzen** [comment]
Thanks for reminder. The `pyproject.toml` already contained the license information but the repository itself lacked it. I added it.

**Comment by vlcinsky** [comment]
Thanks for adding it and also for using MIT one.
