### ISSUE TITLE
Add possible callback to process type and default

### ISSUE THREAD

**Issue by spacemanspiff2007** [mansenfranzen/autodoc_pydantic#100]
I load a ``str`` from a yaml file and convert it into a path object.
It's possible to change certain paths so e.g. logfiles get generated in a different folder.

Currently this
```python
logging: Path = Field(Path('log'), description='Folder where the logs will be written to')
```
renders like that
```
field logging: Optional[pathlib.Path] = WindowsPath('log')
```

However since the user is editing a yaml file I'd like to process both the type and the default value to be a string.
E.g. so it looks like that.
```python
field logging: Optional[str] = 'log'
```

I'm aware that this is a rather special use case. 
So how about a configurable callback that gets inserted [here](https://github.com/mansenfranzen/autodoc_pydantic/blob/36ffae3b96fa7be84f0c7fbf74bfee1db7fcfc5a/sphinxcontrib/autodoc_pydantic/directives/autodocumenters.py#L491).
The callback would get the ``PydanticFieldDocumenter`` and the ``default`` passed in. If it returns a string that's the value for documentation, otherwise ``object_description`` would be called.
For the type I have not yet found the code part where it happens - could you provide me with a hint?

What do you think? Is this something where I can create a PR and you see it getting merged or do you have a better idea how this can achieved?
Thank you for your help!

**Comment by mansenfranzen** [comment]
Hi @spacemanspiff2007 again,

as you've pointed it out, your request is rather special. Supporting callbacks for such selective attributes is unfortunately too specific in my opinion because it introduces too much complexity for the functionality it provides. 

I'm not opposed to callbacks in general but they should have a more general purpose such as passing the docutil content node of an auto-documented object to be modified. Sphinx itself already provides such functionality under the name of [core events](https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx-core-events) which essentially are hooks/callbacks during the doc building process that allows further customization. More concretely, [`object-description-transform`](https://www.sphinx-doc.org/en/master/extdev/appapi.html#event-object-description-transform) might be interesting for you (though I'm not 100% sure that it does what you need).

I might provide a short example in the users FAQ to further customize the rendering of auto-documented objects once I've finished the other issues but this might take some time.

I hope it helps.

**Comment by spacemanspiff2007** [comment]
Thank you for your reply. 
Post processing the node should be enough if I can distinguish that it is a autodoc-pydantic node.
I'll take a look at it and report back. :+1:

**Comment by spacemanspiff2007** [comment]
No luck so far.
I managed to replace the ``pathlib.Path`` and ``Path`` Text objects but then sphinx keeps crashing.
So obviously I must be doing something wrong.

Could you point me in the right direction?
Thank you for your support!

```python
from docutils.nodes import Text


def transform_desc(app, domain, objtype: str, contentnode):
    if objtype != 'pydantic_model':
        return None

    for desc_child in contentnode.children:
        if desc_child.tagname != 'desc':
            continue
        for signature_child in desc_child.children:
            if signature_child.tagname != 'desc_signature':
                continue
            for annotation_child in signature_child.children:
                if annotation_child.tagname != 'desc_annotation':
                    continue
                for pending_xref_child in annotation_child.children:
                    if pending_xref_child.tagname != 'pending_xref':
                        continue
                    for pending_xref_cond in pending_xref_child.children:
                        if pending_xref_cond.tagname != 'pending_xref_condition':
                            continue
                        for i, child in enumerate(pending_xref_cond.children):  # type: int, Text
                            content = child.astext()
                            if content in ('Path', 'pathlib.Path'):
                                pending_xref_cond.children[i] = Text('str')


def setup(app):
    app.connect('object-description-transform', transform_desc)
```

**Comment by mansenfranzen** [comment]
This was indeed more complicated than I've thought and I assume the solution I can offer is not very robust against edge cases. 

Anyway, you were pretty close with your solution. The new `Text` node just needs a valid parent (see content of function `replace_node_text`). I solved it slightly differently, as follows:

```python
from typing import List, Set

from docutils.nodes import Text, Node


def find_tagname_text_matches(node: Node,
                              tag_matches: Set[str],
                              text_matches: Set[str]) -> List[Node]:
    """Find nodes with given `tag_matches` and `text_matches`. Recursively
    iterate children nodes.

    """

    matched_nodes = []
    has_text_child_first = False

    # iterate children
    if node.children:
        for child in node.children:
            child_matches = find_tagname_text_matches(
                node=child,
                tag_matches=tag_matches,
                text_matches=text_matches)
            matched_nodes.extend(child_matches)

        if isinstance(node.children[0], Text):
            has_text_child_first = True

    # handle node itself
    is_pending_xref = node.tagname in tag_matches
    is_text_match = node.astext() in text_matches
    if is_pending_xref and is_text_match and has_text_child_first:
        matched_nodes.append(node)

    return matched_nodes


def replace_node_text(node: Node, replace_text: str):
    """Replaces first children text node with given `text`. Works inplace.

    """

    replace_node = Text(replace_text)
    replace_node.parent = node
    node.children[0] = replace_node


def substitute_texts(node: Node,
                     tag_matches: Set[str],
                     text_matches: Set[str],
                     replace_text: str):
    """Traverse `node` for matching tag names & text content and replace
    text.

    """

    nodes = find_tagname_text_matches(node=node,
                                      tag_matches=tag_matches,
                                      text_matches=text_matches)

    for node in nodes:
        replace_node_text(node=node, replace_text=replace_text)


def transform_desc(app, domain, objtype: str, contentnode):
    if objtype != 'pydantic_field':
        return None

    substitute_texts(node=contentnode.parent,
                     tag_matches={"pending_xref", "pending_xref_condition"},
                     text_matches={"Path", "pathlib.Path"},
                     replace_text="str")


def setup(app):
    app.connect('object-description-transform', transform_desc)

```

This works with my dummy example.  The functions should be generic enough to be adjusted to your needs. However, as stated above, I doubt that this is very robust. For example, if you use [field summary lists](https://autodoc-pydantic.readthedocs.io/en/stable/users/configuration.html#show-field-summary), the shown type differs there and also needs to be modified. Moreover, There might be some cases where the target node to be modified is not `pending_xref` or `pending_xref_condition`. 

In any case, let me know if it works for you.
