### ISSUE TITLE
Show fields from parent model

### ISSUE THREAD

**Issue by nickeldan** [mansenfranzen/autodoc_pydantic#101]
In the following case

```python
class Foo(pydantic.BaseModel):
    '''Foo class'''

    x: str = pydantic.Field(description='The x.')

class Bar(Foo):
    '''Bar class'''

    y: int = pydantic.Field(description='The y.')
```

is there a way to have the documentation for `Bar` show both `x` and `y` as the fields?

**Comment by mansenfranzen** [comment]
Hi @nickeldan,

this has already been answered in #32 and is documented in the users FAQ [here](https://autodoc-pydantic.readthedocs.io/en/stable/users/faq.html#show-inherited-fields-validators).

To improve future search results, what search terms have you used to look for an already existing answer? Your answer will help me to guide new users to the correct answer more quickly.

**Comment by nickeldan** [comment]
Ah, thanks!  I'm not sure how I missed that.

I don't recall what my search terms were.
