### ISSUE TITLE
Does `autodoc_pydantic` work with autoapi?

### ISSUE THREAD

**Issue by csm10495** [mansenfranzen/autodoc_pydantic#138]
I'm not fully initiated into sphinx so some terms may be slightly off so bear with me :) 

I have a project that uses sphinx autoapi to build some rst files from code for docs. I figured adding sphinxcontrib.autodoc_pydantic" as an extension in conf.py would be enough to get the description from pydantic fields in the documentation... but alas it doesn't seem to make a difference.

Does this generally work with projects that generate docs via autoapi?

In my conf.py:

```
..
extensions = [
    "autoapi.extension",
    "sphinxcontrib.autodoc_pydantic",
    "sphinx_rtd_theme",
]
...
html_theme = "sphinx_rtd_theme"

autoapi_type = "python"
autoapi_dirs = ["../src"]
autoapi_keep_files = True
autoapi_python_class_content = 'both'
autoapi_options = ['members', 'undoc-members', 'show-inheritance', 'show-module-summary', 'special-members', 'imported-members']
```

**Comment by mansenfranzen** [comment]
@csm10495 Thanks for raising this question here. It is a very valid question and unfortunately this has not been covered in the docs. 

The short answer is: No. 

I added a section in the user's FAQ in the current dev release, see [here](https://autodoc-pydantic.readthedocs.io/en/v1.8.0-a.2/users/faq.html#autoapi-interoperability). Please let me know if the FAQ answers your question. Also, feel free to drop any comment or alike.

**Comment by csm10495** [comment]
Thanks for the info!

**Comment by mansenfranzen** [comment]
all-contributors please add @csm10495 for question

**Comment by mansenfranzen** [comment]
@all-contributors please add @csm10495 for question
