### ISSUE TITLE
some autodoc-pydantic configuration being ignored for some `automodule` sections

### ISSUE THREAD

**Issue by caseyzak24** [mansenfranzen/autodoc_pydantic#152]
Hi there, I'm seeing some pretty strange behavior when using automodule...

First, I'm using Sphinx 7.0.1 and autodoc-pydantic 1.8.0.

Here is an rst file I have as part of my docs:
```rst
API
===

.. automodule:: generation_models
   :members:
.. automodule:: project_finance
   :members:
```
In case it matters, both of these modules are dependencies of the current project and are installed in the local virtual environment.

This is my conf.py
```python
# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "Tyba API & Data Client"
copyright = "2023, Allen Lawrence, Casey Zak"
author = "Allen Lawrence, Casey Zak"
release = "0.1"

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = ["sphinx.ext.autodoc", "sphinxcontrib.autodoc_pydantic"]

templates_path = ["_templates"]
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "sphinx_material"
html_static_path = ["_static"]

autodoc_pydantic_model_show_json = False
autodoc_pydantic_model_show_config = False
autodoc_pydantic_model_show_validator_members = False
autodoc_pydantic_field_list_validators = False
```
When I run `make html` this is what I see in api.html for an object in the `generation_models` module:

<img width="502" alt="image" src="https://github.com/mansenfranzen/autodoc_pydantic/assets/29411281/7ba81b58-1b58-4034-b4d8-f06b88250041">

Here is the corresponding python snippet:
```python
class ACProductionProfile(BaseModel):
    """_"""

    power: t.List[float]
    ambient_temp: t.Optional[t.List[float]]

    # if ACProductionProfile is allowed to have extra fields in the payload, then a DCProductionProfile payload will be
    # coerced into an ACProductionProfile object if something is wrong with voltage
    class Config:
        extra = "forbid"

    @root_validator(skip_on_failure=True)
    def check_length(cls, values):
        if values["ambient_temp"]:
            _check_lengths({"power": values["power"], "ambient_temp": values["ambient_temp"]})
        return values

    def __len__(self) -> int:
        return len(self.power)
```
The `autodoc_pydantic_model_show_config = False` setting is being ignored but all of the other autodoc-pydantic config settings are honored.

However, this is what I see for an object in the `project_finance` module:

<img width="502" alt="image" src="https://github.com/mansenfranzen/autodoc_pydantic/assets/29411281/5019aa11-89a2-4ad2-987f-3dc06b7491fc">

And here is the corresponding python snippet:
```python
class BaseFinanceInputs(BaseModel):
    """_"""

    frequency: str

    class Config:
        arbitrary_types_allowed = True

    @validator("frequency")
    def check_freq(cls, v):
        assert (
            v in valid_frequencies
        ), f"frequency must be one of {list(valid_frequencies.keys())}"
        return v

    def get_cash_flow(self) -> np.ndarray:
        return cash_flow(capex=self.capex, opex=self.opex, revenue=self.revenue)
```
In this case, `autodoc_pydantic_model_show_json = False` and `autodoc_pydantic_field_list_validators = False` are honored but `autodoc_pydantic_model_show_config = False` and `autodoc_pydantic_model_show_validator_members = False` are not.

Any idea what is going on here? Thanks!

**Comment by caseyzak24** [comment]
In case anyone has looked at my original post, just a heads up that I updated it with a better example

**Comment by mansenfranzen** [comment]
@caseyzak24 Thanks for reporting this issue. It definitely seems like a bug. 

To narrow down the issue, could you please document your models via the [autopydantic_model](https://autodoc-pydantic.readthedocs.io/en/latest/users/usage.html#autopydantic-model) directive? If all the global configurations (set in `conf.py`) such as `autodoc_pydantic_model_show_json` are honored correctly, then it clearly indicates an error regarding the interplay with `autosummary`.

**Comment by caseyzak24** [comment]
@mansenfranzen thanks for the follow up. As you suggested, I used the model directive on just the 2 classes I had given in my example. Unfortunately, the output is the same:
<img width="502" alt="Screen Shot 2023-07-03 at 12 44 18 PM" src="https://github.com/mansenfranzen/autodoc_pydantic/assets/29411281/1df95a36-3d18-4850-8fcc-b90f4ca4c144">

For reference, my conf.py is the same as before and my api.rst now looks like this:

```rst
API
===

..
    .. automodule:: tyba_client.client
       :members:
    .. automodule:: generation_models
       :members:
    .. automodule:: project_finance
       :members:

.. autopydantic_model:: generation_models.ACProductionProfile
.. autopydantic_model:: project_finance.BaseFinanceInputs
```

Happy to try other things and generally help with the fix any way I can!

**Comment by mansenfranzen** [comment]
Okay, I just took a look at the [documentation](https://autodoc-pydantic.readthedocs.io/en/stable/users/configuration.html#show-config-summary) again. The configuration name is not correct. Actually, it's `autodoc_pydantic_model_show_config_summary` and not `autodoc_pydantic_model_show_config`. Please recheck if the configuration names match exactly. This issue has occurred to me several times, too ;-).

**Comment by caseyzak24** [comment]
Wow @mansenfranzen I was somewhat relieved when you first said it was a bug because at least I wasn't wasting anyone's time. Turns out that is exactly what I was doing (sigh). Once I had the correctly named configs it all looks good.

However, the reason I incorrectly named the `autodoc_pydantic_model_show_config_summary` config is that in autodoc_pydantic docs under "Configuration", the top paragraph has the incorrect name:
<img width="763" alt="Screen Shot 2023-07-03 at 1 38 32 PM" src="https://github.com/mansenfranzen/autodoc_pydantic/assets/29411281/dbc7dfb9-8660-4e77-acda-262d004f164a">

Happy to submit a PR for that small typo fix if you'd like.

Thanks again for your help!

**Comment by mansenfranzen** [comment]
No worries. 

I'm very happy to merge a pull requests which are not mine ;-).

**Comment by mansenfranzen** [comment]
@all-contributors please add @caseyzak24 for docs
