### ISSUE TITLE
Import error since pydantic v2 release 

### ISSUE THREAD

**Issue by tkaraouzene** [mansenfranzen/autodoc_pydantic#153]
Hi and thanks for your great work!

Since pydantic v2 release I have following error when I try to import autodoc_pydantic:

```bash
Extension error:
Could not import extension sphinxcontrib.autodoc_pydantic (exception: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.0/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.0/u/import-error)   
nox > Command sphinx-build 'C:\Users\path\to\my\project\ci_reports\documentation' -D project=peal -D version=0.1.0 -a -E failed with exit code 2
```

It seems it is becaus your projecty doesn't have upper bounds for pydantic dependency:

from your pyproject.tom:

``pydantic = ">=1.5"``

**Comment by mansenfranzen** [comment]
@all-contributors please add @tkaraouzene for bug

**Comment by mansenfranzen** [comment]
@tkaraouzene Thanks for pointing out the issue. The new release including the bug fix has just landed on pypi.

**Comment by PeterKraus** [comment]
Is there a plan to get the library working with `pydantic~=2.0`?
