### ISSUE TITLE
Deprecation warning for `ObjectMember` for Sphinx 7.2.2

### ISSUE THREAD

**Issue by j-carson** [mansenfranzen/autodoc_pydantic#174]
`/.nox/docs/lib/python3.10/site-packages/sphinxcontrib/autodoc_pydantic/directives/autodocumenters.py:135: RemovedInSphinx80Warning: The tuple interface of ObjectMember is deprecated. Use (obj.__name__, obj.object) instead.`

**Comment by mansenfranzen** [comment]
@j-carson Thx for reporting the issue and the PR. I will take a closer look during the next days.

**Comment by mansenfranzen** [comment]
@all-contributors please add @rafa-guedes for code
