### ISSUE TITLE
Add `pydantic` classifier to help finding package

### ISSUE THREAD

**Issue by caerulescens** [mansenfranzen/autodoc_pydantic#181]
I already knew about this package, and I tried to find it using filters in PyPi but couldn't. 

see PRs #179 and #180.

**Comment by mansenfranzen** [comment]
@caerulescens Thanks a lot for reporting this and providing two PRs for pydantic 1 and 2. It will be part of the next release.

**Comment by mansenfranzen** [comment]
Fixed via #179 and #180
