### ISSUE TITLE
Allow `autodoc_pydantic_field_signature_prefix` to be empty

### ISSUE THREAD

**Issue by azmeuk** [mansenfranzen/autodoc_pydantic#188]
Hi.
Currently `autodoc_pydantic_field_signature_prefix` cannot be `None` (else it raises an exception while documentation is built) or an empty string (else the default `attribute` value is used).
I would love to be able to disable prefixes with `autodoc_pydantic_field_signature_prefix = None`.
What do you think?

**Comment by mansenfranzen** [comment]
Hi @azmeuk,

thanks for providing the feature request. It sounds reasonable to me. I will put it on the roadmap for the next feature release.

**Comment by mansenfranzen** [comment]
@all-contributors please add @azmeuk for bug

**Comment by azmeuk** [comment]
@mansenfranzen Sorry for the long silence.
I just tested and it renders exactly as I wished :ok_hand: 
Thank you very much!
