### ISSUE TITLE
Model Field Output

### ISSUE THREAD

**Issue by TheBeardedBerserkr** [mansenfranzen/autodoc_pydantic#2]
When  I generate the html for a my model none of the fields are populating. 

The docs just generate something along the lines of:

pydantic model MyModel [source]
   This is my doc string.
  Show Json Schema

I'm generating the page with the 
`..automodule:: package.MyModel
   :members:`

Am I supposed to have a setting marked for field population?

**Comment by TheBeardedBerserkr** [comment]
To be a little more clear how do I get these:
>provides default values, alias and constraints for model fields
to generate? Is it a conf.py setting?

**Comment by mansenfranzen** [comment]
Hi, 

thanks for opening the first issue ;-). Do your pydantic fields have doc strings? If not, sphinx autodoc will ignore them. To include undocumented members, add `:undoc-members:` :

```
.. automodule:: package.MyModel 
   :members:
   :undoc-members:
```

Please let me know if this works for you.

In any case, it seems to be a good idea to include undocumented pydantic fields regardless of the `:undoc-members:`  option. This should be configurable of course.

**Comment by TheBeardedBerserkr** [comment]
That worked! 
I figured it was a me thing! Still new to all this, pydantic, sphinx, autodocs so forgive the ignorance!
Hopefully all the issues are as easy as this one!

**Comment by mansenfranzen** [comment]
I'm glad it helped and thanks for the issue any. It inspired me to provide an additional default to automatically set `:undoc-members:` for pydantic models.
