### ISSUE TITLE
erdantic v1.0 coming soon

### ISSUE THREAD

**Issue by jayqi** [mansenfranzen/autodoc_pydantic#241]
Hello,

I'm the maintainer of erdantic, and I wanted to let you know that erdantic v1.0 is coming soon. It's available right now as a pre-release version v1.0.0rc1 and can be installed with `pip install erdantic --pre`. Please let me know how I can help to make sure that things go smoothly for autodoc_pydantic. 

In general, there shouldn't be any breaking changes to the most commonly used APIs. I took a look through the repository, and I believe this is the spot where erdantic is actually called:

https://github.com/mansenfranzen/autodoc_pydantic/blob/c07d1f2223897d2fa5983423bbe73ac73a624fee/sphinxcontrib/autodoc_pydantic/directives/autodocumenters.py#L360-L361

As far as I can tell, there should be no breaking changes there, and that code should continue to work without error. 

The backend of erdantic has changed significantly in v1.0 and, in general, I am hoping it will be easier for users to customize diagrams. (It includes functionality for https://github.com/drivendataorg/erdantic/issues/78.) A summary of changes is available [here](https://erdantic.drivendata.org/v1.0/changelog/). 

Thanks for including erdantic integration in your project! If you have any questions, please let me know.

**Comment by mansenfranzen** [comment]
Hi @jayqi,

thanks a lot for you work and the heads up! The new release will help to simplify our tests incorporating erdantic via removing the graph label from the test data which varies across different erdantic versions:

https://github.com/mansenfranzen/autodoc_pydantic/blob/87923a128d32343a6291d29c996a413994ede89c/tests/test_configuration_model.py#L101-L166

By the way, I'm also convinced that your new release greatly improves the customizability of the diagrams with great benefit for end users.

When do you intend to release the new version?

**Comment by jayqi** [comment]
Thanks for the feedback! I'm thinking about waiting through this weekend in case anybody is still going to test against 1.0.0rc1. So doing the release probably Monday or Tuesday.

**Comment by jayqi** [comment]
@mansenfranzen v1.0 is out now on PyPI and conda-forge. Let me know if you have any questions or run into any issues. I'm leaving this issue open in case you want to use it to track something, but no need to keep it open on my account.

**Comment by mansenfranzen** [comment]
I just came across an issue with generics and typevar for which I opened an issue https://github.com/drivendataorg/erdantic/issues/114.
