### ISSUE TITLE
Bug: Failed import on sphinx 7.3

### ISSUE THREAD

**Issue by j-carson** [mansenfranzen/autodoc_pydantic#255]
Sphinx 7.3 stopped exporting py_sig_re

```
Extension error:
Could not import extension sphinxcontrib.autodoc_pydantic (exception: cannot import name 'py_sig_re' from 'sphinx.domains.python'
```

Addressed in https://github.com/sphinx-doc/sphinx/issues/12303.

**Comment by j-carson** [comment]
Commit where it disappeared https://github.com/sphinx-doc/sphinx/pull/12297/files

**Comment by lwasser** [comment]
hi! we have the [same issue / same error here](https://github.com/stravalib/stravalib/actions/runs/8730196389/job/23955197530#step:8:21) . our build runs fine on sphinx 7.3.5 so I believe the 7.3.6 released triggered this issue the autodoc_pydantic! Many thanks for all of the work you all are doing on this extension 🙌

**Comment by mansenfranzen** [comment]
@all-contributors please add @lwasser for issue

**Comment by mansenfranzen** [comment]
@all-contributors please add @lwasser for bug

**Comment by mansenfranzen** [comment]
Closed by @AA-Turner via https://github.com/sphinx-doc/sphinx/issues/12303

**Comment by lwasser** [comment]
Thank you @mansenfranzen !
