### ISSUE TITLE
Exception during build: `AttributeError: 'tuple' object has no attribute 'rebuild'`

### ISSUE THREAD

**Issue by bruno-f-cruz** [mansenfranzen/autodoc_pydantic#275]
Hi, 
When attempting to build the website using sphinx I get the following error:

```
Exception occurred:
  File "<..>\.venv\Lib\site-packages\sphinx\config.py", line 433, in __iter__
    yield ConfigValue(name, getattr(self, name), opt.rebuild)
                                                 ^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'rebuild'
```

Any idea where this could be coming from? I am using Pydantic 2.7 and the following extensions:

```python
extensions = [
    "sphinx-jsonschema",
    "sphinx_jinja",
    "sphinx.ext.napoleon",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "sphinx.ext.githubpages",
    "sphinx.ext.linkcode",
    "myst_parser",
    "sphinxcontrib.autodoc_pydantic",
]
```

Also attaching the log in case its helpful
[sphinx-err-497mbx2s.log](https://github.com/mansenfranzen/autodoc_pydantic/files/15099838/sphinx-err-497mbx2s.log)
Thanks!

**Comment by Carson-Shaar** [comment]
Hey @bruno-f-cruz, ran into this issue as well (#274).  Downgrade Sphinx to 7.2.6 and it will fix it

**Comment by bruno-f-cruz** [comment]
Literally just tried this and its working, thanks :)
Closing this as a duplicate of #274
