### ISSUE TITLE
`pd.DataFrame` breaks JSON schema generation

### ISSUE THREAD

**Issue by thomas-pedot** [mansenfranzen/autodoc_pydantic#28]
When using Arbitrary type we cannot serialize to a JSON Schema.

Work
```
PandasDataFrame = TypeVar('pd.DataFrame')

class Model(BaseModel):
    pandasDF:  PandasDataFrame 
```

Doesnot work
```
class Model(BaseModel):
    pandasDF:  pd.DataFrame
    class Config:
        arbitrary_types_allowed = True # pd.DataFrame allowed
```

Following error is raised when building the docs:

`ValueError: Value not declarable with JSON Schema, field: name='inputs_DataFrame' type=DataFrame required=True`

**Comment by mansenfranzen** [comment]
Thanks for the bug report. I can reproduce the issue. Be aware there is already a mechanism to capture fields which are not JSON serializable (see warning [here](https://autodoc-pydantic.readthedocs.io/en/latest/configuration.html#show-schema-json) in the docs). However, the pandas dataframe dtype currently escapes this safety guard.

**Comment by mansenfranzen** [comment]
@thomas-pedot PR #30 addresses the current issue allowing you to define how `autodoc_pydantic` should behave in case a pydantic field can't be JSON serialized properly. Please see the updated [docs](https://autodoc-pydantic.readthedocs.io/en/v1.3.2-a.2/configuration.html#show-schema-json-error-strategy) on this.

Before merging the related PR, it would be great if you could test the bug fix on your site to confirm that my test case did indeed capture the incorrect behavior which you've encountered. To do so, please install the current dev release in your doc-building-environment via pip install `git+git://github.com/mansenfranzen/autodoc_pydantic.git@v1.3.2-a.2` and rebuild your docs.

**Comment by mansenfranzen** [comment]
Closing this issue via #30. Please feel free to reopen for further discussions.
