### ISSUE TITLE
Option to display fields names without their class name in the TOCs

### ISSUE THREAD

**Issue by azmeuk** [mansenfranzen/autodoc_pydantic#287]
Thanks to #285 I can remove the signature prefix from the fields. This makes it less confusing for users who do want to use and parameter my application, but does not care about python things:

![Capture d’écran du 2024-05-17 22-39-11](https://github.com/mansenfranzen/autodoc_pydantic/assets/60163/7cb584f0-362d-43bc-9cde-406d2cd5a4c6)

However as you see in the screenshot, the fields are referenced in the sidebar TOC with their class name attached.

It would be nice if there was a way to only display fields names in the TOC, for instance `THEME` instead of `CoreSettings.THEME`.

What do you think?

**Comment by mansenfranzen** [comment]
Hi @azmeuk,

thanks for raising the issue here! 

The TOC generation is not part of `autodoc_pydantic`. This feature request belongs to Sphinx in case you're using the builtin `.. toctree::` directive. 

I hope this helps to guide you into the correct direction.

Feel free to reopen :-)

**Comment by mansenfranzen** [comment]
@allcontributors please add @azmeuk for question
