### ISSUE TITLE
Handle Ellipsis default value

### ISSUE THREAD

**Issue by davidchall** [mansenfranzen/autodoc_pydantic#34]
pydantic uses `Field(default = ...)` to indicate that a field is required ([see docs](https://pydantic-docs.helpmanual.io/usage/schema/#field-customisation)).

Currently `autodoc_pydantic` will output things like:

> _field_ name: _str = Ellipsis_

which can be a bit confusing. Perhaps it could instead output something like:

> _field_ name: _str **[Required]**_

**Comment by mansenfranzen** [comment]
Thanks a lot for the request. I totally agree that this could be improved. It will be included in the next release.

**Comment by mansenfranzen** [comment]
I really like this modification and hence it is already included in the current dev release. Please checkout the new dev release via `pip install git+git://github.com/mansenfranzen/autodoc_pydantic.git@v1.4.0-a.1` to test it in your build environment.

To preview those changes, you can visit the current dev documentation with explained [configuration](https://autodoc-pydantic.readthedocs.io/en/feature_field_value_required34/configuration.html#show-required) and an [example](https://autodoc-pydantic.readthedocs.io/en/feature_field_value_required34/examples.html#target.example_setting.ExampleSettings.field_without_default).

**Comment by davidchall** [comment]
Excellent - thank you for the quick response! ⚡  I confirm it's working at my end 👍

**Comment by mansenfranzen** [comment]
Closing this via #35.
