### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by mansenfranzen** [mansenfranzen/autodoc_pydantic#39]
Initial setup for adding contributors via [all-contributors bot](https://github.com/all-contributors/app).

**Comment by mansenfranzen** [comment]
@all-contributors please add @mansenfranzen for maintenance, doc, test and content

**Comment by mansenfranzen** [comment]
@all-contributors please add @TheBeardedBerserkr for ideas
@all-contributors please add @vlcinsky for security
@all-contributors please add @antvig for bug and userTesting
@all-contributors please add @roguh for ideas
@all-contributors please add @ybnd for bug and userTesting
@all-contributors please add @tahoward for bug and userTesting
@all-contributors please add @thomas-pedot for bug and userTesting
@all-contributors please add @matutter for bug and userTesting
@all-contributors please add @roguh for ideas and userTesting

**Comment by mansenfranzen** [comment]
@all-contributors please add @TheBeardedBerserkr for ideas

**Comment by mansenfranzen** [comment]
@all-contributors please add @vlcinsky for security

**Comment by mansenfranzen** [comment]
@all-contributors please add @antvig for bug and userTesting

**Comment by mansenfranzen** [comment]
@all-contributors please add @roguh for ideas

**Comment by mansenfranzen** [comment]
@all-contributors please add @ybnd for bug and userTesting

**Comment by mansenfranzen** [comment]
@all-contributors please add @tahoward for bug and userTesting

**Comment by mansenfranzen** [comment]
@all-contributors please add @thomas-pedot for bug and userTesting

**Comment by mansenfranzen** [comment]
@all-contributors please add @matutter for bug and userTesting

**Comment by mansenfranzen** [comment]
@all-contributors please add @davidchall for ideas and userTesting

**Comment by mansenfranzen** [comment]
@all-contributors please add @Yoshanuikabundi for ideas and research

**Comment by mansenfranzen** [comment]
Finished adding all contributors.

**Comment by slamer59** [comment]
@mansenfranzen I didn't see any issues on my side ! Thanks

Sorry for the late reply I was on holidays. 
Regards
