### ISSUE TITLE
Sphinx 4.3 will include a breaking change for autodoc_pydantic

### ISSUE THREAD

**Issue by Yoshanuikabundi** [mansenfranzen/autodoc_pydantic#62]
Hi! I've been lending a hand to contributing to Sphinx itself and discovered that my project no longer built on the upcoming release's branch. I bisected and reported this issue as https://github.com/sphinx-doc/sphinx/issues/9832 and the wonderful Jakob Andersen has tracked the problem down to a change in signature for `get_signature_prefix` (https://www.sphinx-doc.org/en/master/changes.html#id2), which is apparently overwritten by autodoc_pydantic.

His comment is here: https://github.com/sphinx-doc/sphinx/issues/9832#issuecomment-963919555

He's written a [mitigation](https://github.com/sphinx-doc/sphinx/pull/9833) but the behaviour will still be broken, just with a clearer error message. The release is expected to come out in the [next few days](https://github.com/sphinx-doc/sphinx/issues/9824). Thought you'd want a heads up!

**Comment by jakobandersen** [comment]
I suggest either requiring Sphinx 4.3 a minimum version, or based on the Sphinx version return either a string or a list of nodes.

**Comment by mansenfranzen** [comment]
@Yoshanuikabundi Thanks for reporting the issue here and creating https://github.com/sphinx-doc/sphinx/issues/9832. I will take care to make `autodoc_pydantic` work with sphinx version 4.3 in the next release. The required adjustment should not be too difficult.

@jakobandersen Thanks for providing the mitigation in the meanwhile.

**Comment by mansenfranzen** [comment]
@all-contributors please add @Yoshanuikabundi for test

**Comment by mansenfranzen** [comment]
@all-contributors please add @jakobandersen for code

**Comment by mansenfranzen** [comment]
@jakobandersen and @Yoshanuikabundi compatibility issues with sphinx 4.3 have been fixed and will be available in in the upcoming release v.1.5.1.
