### ISSUE TITLE
Add `sphinx-extension` GitHub topic

### ISSUE THREAD

**Issue by astrojuanlu** [mansenfranzen/autodoc_pydantic#63]
I usually browse https://github.com/topics/sphinx-extension to discover new extensions, would be great to have this extension listed there :)

**Comment by mansenfranzen** [comment]
Thanks for sharing - I didn't know about github topics. I will add it there soon :-)

**Comment by mansenfranzen** [comment]
@all-contributors please add @astrojuanlu for content

**Comment by mansenfranzen** [comment]
Done
