### ISSUE TITLE
Support for Union with ForwardRef

### ISSUE THREAD

**Issue by Czaki** [mansenfranzen/autodoc_pydantic#98]
for code:
```python
Node = ForwardRef('Node')

class Node(BaseModel):
    left: Union[Node, Leaf]
    op: str
    right: Union[Node, Leaf]
```

there was warning `/home/czaki/Projekty/PartSeg/docs/autodoc_pydantic.rst: WARNING: JSON schema can't be generated for 'PartSegCore.analysis.measurement_base.Node' because the following pydantic fields can't be serialized properly: ['left', 'right'].
`

in this code 
https://github.com/mansenfranzen/autodoc_pydantic/blob/36ffae3b96fa7be84f0c7fbf74bfee1db7fcfc5a/sphinxcontrib/autodoc_pydantic/inspection.py#L183-L189

there is no check for `sub_fields`:
https://github.com/samuelcolvin/pydantic/blob/fbf8002cefd1ba7b263f63545fff2e48a378189d/pydantic/typing.py#L445-L458

in my case `field.type_` is `typing.Union[ForwardRef('Node'), PartSegCore.analysis.measurement_base.Leaf]` but `field.sub_fields` is `[ModelField(name="left_ForwardRef('Node')", type=Node, required=True), ModelField(name='left_Leaf', type=Leaf, required=True)]` 

So all data are available in data structures.

**Comment by mansenfranzen** [comment]
@Czaki Thanks for sharing this issue. It is definitely a bug. I can reproduce the behavior and it boils down to recursively check `sub_fields` as you have pointed it out. It will be fixed in the upcoming release.

**Comment by mansenfranzen** [comment]
@Czaki This should be fixed via #102.

Before merging the related PR, it would be great if you could test the bug fix on your site to confirm that my test case did indeed capture the incorrect behavior which you've encountered. To do so, please install the current dev release in your doc-building-environment via `pip install git+https://github.com/mansenfranzen/autodoc_pydantic.git@v1.6.2-a.1` and rebuild your docs.

**Comment by mansenfranzen** [comment]
@all-contributors please add @Czaki for bug

**Comment by mansenfranzen** [comment]
@Czaki Please feel free to reopen this ticket if the issue persists.
